AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FormatString:
  EnforcedStyle: percent

Style/IfUnlessModifier:
  Enabled: false


Style/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8
